---
- name: Создание пользовательского пула и виртуальных машин
  # Цель всегда all, а фильтрацию делает флаг -l со списком хостов
  hosts: all
  become: true
  gather_facts: false
  any_errors_fatal: false

  # Каждому хосту в сессии присваиваем переменную host, равную его собственному имени
  vars:
    host: "{{ inventory_hostname }}"

  pre_tasks:
    - name: Валидация входных параметров (наличие user)
      fail:
        msg: "Ошибка! Вы должны передать параметр user. Пример: -e 'user=ivanov'"
      when: user is not defined or user | length == 0
      run_once: true # Проверяем всего один раз на старте

    - name: Проверка, что текущий хост существует в файле инвентаря
      fail:
        msg: "Ошибка! Хост '{{ inventory_hostname }}' не найден в вашем файле инвентаря. Проверьте правильность написания."
      when: inventory_hostname not in groups['all']

  roles:
    - role: vlab
      vars:
        vlab_action: define_user_pool
