---
# Запрос имени и пароля администратора
- import_playbook: prompt.yml

- name: Проверка входных параметров
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Валидация входных параметров (наличие host и user)
      fail:
        msg: "Ошибка! Вы должны передать параметры host и user. Пример: -e 'host=lws-01 user=ivanov'"
      when: (user is not defined) or (host is not defined)

    - name: Проверка, что указанный хост существует в файле инвентаря
      fail:
        msg: "Ошибка! Хост '{{ host }}' не найден в вашем файле инвентаря. Проверьте правильность написания."
      # Проверка выполнится, только если хост вообще был передан, чтобы не вызвать ошибку синтаксиса
      when: (host is defined) and (host not in groups['all'])

- name: Создание пользовательского пула и виртуальных машин
  hosts: "{{ host }}"
  become: true

  roles:
    - role: vlab
      vars:
        vlab_action: define_user_pool
