---
# Запрос имени и пароля администратора
# - import_playbook: prompt.yml

- name: Оркестрация удаления учетной записи обучаемого
  hosts: "{{ host }}"
  become: true

  pre_tasks:
    - name: Валидация входных параметров (наличие host и user)
      fail:
        msg: "Ошибка! Не задан параметр host и/или user. Пример: -e 'host=lws-01 user=ivanov'"
      when: (user is not defined) or (host is not defined)
      run_once: true

    - name: Проверка наличия хоста в файле инвентаря
      fail:
        msg: "Ошибка! Хост '{{ host }}' не найден в вашем файле инвентаря"
      when: host not in groups['all']

    - name: Проверка существования пула для пользователя {{ user }}
      command: "virsh pool-info {{ user }}"
      register: pool_check
      # Игнорировать ошибку, если пула нет (virsh вернет code > 0)
      failed_when: false
       # Задача только читает данные, ничего не меняя
      changed_when: false

    - name: Прерывание плейбука, если пул пользователя существует
      fail:
        msg: "Прерывание! Пул для пользователя '{{ user }}' существует. Удалите пул и повторите попытку"
       # Если rc == 0, значит команда virsh выполнилась успешно и пул найден
      when: pool_check.rc == 0

  roles:
    - role: users
      vars:
        user_action: delete
