---
- name: Оркестрация удаления учетной записи обучаемого
  hosts: all  # Фильтрация полностью управляется вашим флагом -l в bash
  become: true
  gather_facts: false
  any_errors_fatal: false

  # ВОЗВРАЩАЕМ СОВМЕСТИМОСТЬ С РОЛЯМИ:
  # Каждому хосту в сессии присваиваем переменную host, равную его собственному имени.
  vars:
    host: "{{ inventory_hostname }}"

  pre_tasks:
    - name: Валидация входных параметров (наличие user)
      fail:
        msg: "Ошибка! Не задан параметр user. Пример: -e 'user=ivanov'"
      when: user is not defined or user | length == 0
      run_once: true # Достаточно проверить один раз для всего запуска

    - name: Проверка наличия текущего хоста в инвентаре
      fail:
        msg: "Ошибка! Хост '{{ inventory_hostname }}' не найден в файле инвентаря"
      when: inventory_hostname not in groups['all']

  roles:
    - role: users
      vars:
        user_action: delete
