---
- name: Опрос учетных данных SSH и SUDO
  hosts: all
  gather_facts: false
  vars_prompt:
    - name: input_user
      prompt: "Введите имя учетной записи администратора (administrator)"
      private: false

    - name: input_password
      prompt: "Введите пароль администратора или Enter для использования ключей"
      private: true

  tasks:
    - name: Сохранение настроек авторизации на время текущей сессии
      # Выполняем только один раз для каждого хоста
      set_fact:
        ansible_user: "{{ input_user if input_user | length > 0 else 'administrator' }}"
        ansible_password: "{{ input_password if input_password | length > 0 else omit }}"
        ansible_become_password: "{{ input_password if input_password | length > 0 else omit }}"
