---
- name: Получение данных о пользователе из passwd
  ansible.builtin.getent:
    database: passwd
    key: "{{ user }}"
    fail_key: false

- name: Создание переменной is_user_exist
  ansible.builtin.set_fact:
    is_user_exist: "{{ getent_passwd[user] is defined and getent_passwd[user] is sequence }}"

- name: Уведомление об отсутствии учетной записи
  ansible.builtin.debug:
    msg: "Пользователь '{{ user }}' не найден на хосте {{ inventory_hostname }}"
  when: not is_user_exist

- name: Удаление учетной записи пользователя и его домашней директории
  ansible.builtin.user:
    name: "{{ user }}"
    state: absent
    remove: yes # Полностью удаляет хоум-директорию и почтовый ящик
    force: yes  # Принудительно удаляет, даже если есть запущенные процессы пользователя
  when: is_user_exist
