---
- name: Создание первичной группы learners в системе
  group:
    name: learners
    state: present

- name: Создание новой учетной записи или обновление параметров существующей
  user:
    name: "{{ user }}"
    group: learners
    groups:
      - kvm
      - libvirt
      - libvirt-qemu
      - libvirt-admin
    append: yes
    shell: /bin/bash
    state: present
    create_home: yes

- name: Установка пароля для новой учетной записи
  shell: "echo '{{ user }}:{{ user_password }}' | chpasswd"
  no_log: true
  when: not is_user_exist
