---
- name: Проверка и генерация SSH-ключа RSA на localhost
  command: >
    ssh-keygen -t rsa -b 4096 -f {{ lookup('env', 'HOME') }}/.ssh/id_rsa -N ""
  args:
    creates: "~/.ssh/id_rsa"
  delegate_to: localhost
  become: false
  run_once: true

- name: Добавление SSH-ключа в доверенные
  authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
    state: present

- name: Оптимизация параметров пересборки initrd.img
  replace:
    path: /etc/initramfs-tools/initramfs.conf
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - { regexp: '^MODULES=.*', replace: 'MODULES=dep' }
    - { regexp: '^COMPRESS=.*', replace: 'COMPRESS=lz4' }

- name: Копирование ISO-образов репозиториев Astra Linux в системный пул
  synchronize:
    # Слэш на конце src задает копирование содержимого каталога, а не самого каталога
    src: files/images/
    dest: /var/lib/libvirt/images/
    recursive: yes
    delete: no
    archive: yes

- name: Монтирование ISO-образов репозиториев Astra Linux
  mount:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    fstype: iso9660
    opts: loop,ro,nofail
    state: mounted
  loop:
    - src: /var/lib/libvirt/images/astra-1.7_x86-64.iso
      path: /srv/repo/alse/main
    - src: /var/lib/libvirt/images/main_update-1.7.6.15-15.11.24_17.20.iso
      path: /srv/repo/alse/update-main

- name: Обновление кэша apt и установка nftables и rsync
  apt:
    name:
      - nftables
      - rsync
    state: present
    update_cache: yes
    cache_valid_time: 3600
  # Скрыть скрыть подробный вывод в stdout
  no_log: true
