---
- name: Поиск deb-файлов для установки novnc
  find:
    paths: "{{ role_path }}/files"
    patterns: "*.deb"
  register: deb_files
  delegate_to: localhost
  become: false

- name: Создание временной директории на удаленном хосте
  tempfile:
    state: directory
    suffix: _debs
  register: remote_tmp_dir

- name: Копирование deb-пакетов на удаленный хост
  copy:
    src: "{{ item.path }}"
    dest: "{{ remote_tmp_dir.path }}/"
  loop: "{{ deb_files.files }}"

- name: Установка скопированных deb-пакетов через apt
  apt:
    deb: "{{ remote_tmp_dir.path }}/{{ item.path | basename }}"
  loop: "{{ deb_files.files }}"
  become: true

- name: Удаление временной директории с удаленного хоста
  file:
    path: "{{ remote_tmp_dir.path }}"
    state: absent
  become: true
