#!/usr/bin/env python3

import logging
import os
import re
import subprocess
import sys
import time
from datetime import datetime

# Настройка путей
TIMESHIFT_FILE = "/etc/timeshift"
STAMP_FILE = "/run/timemachine.stamp"

# Настройка конфигурации логирования
logging.basicConfig(
    level=logging.INFO,
    format='[%(levelname)s] %(message)s',
)

def get_boot_timestamp():
    """Возвращает Unix Timestamp старта текущей сессии"""
    try:
        with open("/proc/stat", "r") as f:
            for line in f:
                if line.startswith("btime"):
                    return int(line.split()[1])
        logging.error("Маркер btime не найден в /proc/stat")
        return None
    except Exception as e:
        logging.error(f"Не удалось прочитать /proc/stat: {e}")
        return None

def get_down_timestamp():
    """Возвращает Unix Timestamp завершения предыдущей сессии"""
    try:
        # Попытка вычисления времени выключения по журналу journalctl
        # не работает, если журнал на файловой системе tmpfs
        result = subprocess.run(
            [
                "journalctl",
                "-b",
                "-1",
                "-n",
                "1",
                "--output=short-unix",
            ],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True,
            check=True,
        )
        lines = result.stdout.strip().split("\n")
        if lines and lines[0]:
            event_timestamp = int(lines[0].split(".")[0])
            return event_timestamp

    except (subprocess.CalledProcessError, ValueError, IndexError) as e:
        logging.warning(e)

    try:
        # Попытка вычисления времени выключения по журналу wtmp
        output = subprocess.check_output("last -x shutdown -F | head -n 1", shell=True, text=True).strip()
        print(output)
        
        # Поиск первой даты по шаблону "Ммм ДД ЧЧ:ММ:СС ГГГГ"
        match = re.search(r'([A-Z][a-z]{2}\s+\d+\s+\d{2}:\d{2}:\d{2}\s+\d{4})', output)
        if match:
            dt = datetime.strptime(match.group(1), "%b %d %H:%M:%S %Y")
            return int(dt.timestamp())
            
        logging.error("Не удалось распарсить дату выключения")
    except Exception as e:
        logging.error(e)

    return None

def main(timeshift_file=TIMESHIFT_FILE):
    """Рассчитать и вернуть временной сдвиг относительно текущего времени, при критичных ошибках ноль"""

    # Защита от повторного запуска в рамках одной сессии ОС
    if os.path.exists(STAMP_FILE):
        logging.info("Корректировка уже выполнялась в этой сессии.")
        return current_shift

    try:
        with open(timeshift_file, "r") as f:
            content = f.read().strip()
            if not content:
                logging.error(f"Файл {timeshift_file} пуст.")
                return 0
            current_shift = int(content)
    except ValueError:
        logging.error(f"Содержимое файла {timeshift_file} не является числом.")
        return 0
    except IOError as e:
        logging.error(f"Ошибка ввода-вывода {e}")
        return 0

    # Получение времени включения машины
    boot_timestamp = get_boot_timestamp()
    if boot_timestamp is None:
        logging.critical("Не удалось определить время включения.")
        return current_shift

    # Получение времени выключения
    down_timestamp = get_down_timestamp()
    if down_timestamp is None:
        logging.critical("Не удалось определить время выключения.")
        return current_shift

    # Проверка условий и расчет времени простоя в выключенном состоянии
    if boot_timestamp < down_timestamp:
        logging.critical("Время текущей сессии меньше времени предыдущей.")
        return current_shift

    downtime = boot_timestamp - down_timestamp
    logging.info(f"Первый запуск после загрузки. Расчетный downtime: {downtime} сек.")

    # Корректировка файла со смещением времени
    try:
        # Вычисление и запись нового смещения
        new_shift = current_shift - downtime
        with open(timeshift_file, "w") as f:
            f.write(str(new_shift) + "\n")
        logging.info(f"Смещение успешно обновлено.")

        # Создание флаг-файла для блокирования повторных запусков в одной сессии ОС
        with open(STAMP_FILE, "w") as f:
            f.write(datetime.now().strftime('%d.%m.%Y %H:%M:%S'))
        logging.info(f"Создан маркер сессии: {STAMP_FILE}")

        return new_shift

    except IOError as e:
        logging.error(f"Ошибка ввода-вывода {e}")
        return 0

if __name__ == "__main__":
    main()
