---
- name: Удаление межсетевого экрана ufw
  apt:
    name: ufw
    state: absent
    purge: yes

- name: Настройка правил межсетевого экрана nftables из шаблона
  copy:
    src: nftables.conf
    dest: /etc/nftables.conf
    owner: root
    group: root
    mode: '0644'
    # Проверка синтаксиса конфига утилитой nft перед тем, как применить его
    validate: /usr/sbin/nft -c -f %s
  # Триггер, вызывающий обработчик, если файл изменился
  notify: Перезапуск nftables 

- name: Запуск nftables
  service:
    name: nftables
    state: started
    enabled: yes
