---
# Если общая для всех обучаемых группа learners создаваться не будет,
# то здесь и в последующих задач использовать парамерт group: "{{ user }}"
- name: Рекурсивное создание структуры каталогов для пользовательского пула
  file:
    path: "{{ user_pool_path }}"
    state: directory
    owner: "{{ user }}"
    group: "learners"
    mode: '0711'

- name: Проверка наличия пользовательского пула с именем обучаемого
  command: virsh pool-info {{ user_pool_name }}
  register: pool_check
  failed_when: false
  changed_when: false

- name: Регистрация, запуск и добавление пользовательского пула в автозагрузку
  command: "{{ item }}"
  with_items:
    - "virsh pool-define-as {{ user_pool_name }} dir --target {{ user_pool_path }}"
    - "virsh pool-start {{ user_pool_name }}"
    - "virsh pool-autostart {{ user_pool_name }}"
  when: pool_check.rc != 0

- name: Принудительное обновление пула
  command: "virsh pool-refresh {{ user_pool_name }}"
  failed_when: false
  changed_when: false

- name: Поиск базовых образов qcow2 в системном пуле хранения
  find:
    paths: "{{ system_pool_path }}"
    patterns: "*.qcow2"
  register: base_images

- name: Формирование списка из имен виртуальных машин
  set_fact:
    user_domains: "{{ base_images.files | map(attribute='path') | map('basename') | map('regex_replace', '\\.qcow2$', '') | list }}"

- name: Создание оверлейных дисков в пользовательском пуле для всех базовых образов qcow2
  command: >
    qemu-img create -f qcow2 -F qcow2 
    -b "{{ system_pool_path }}/{{ item }}.qcow2" 
    "{{ user_pool_path }}/{{ item }}.qcow2"
  loop: "{{ user_domains }}"
  args:
    creates: "{{ user_pool_path }}/{{ item }}.qcow2"

- name: Восстановление прав владельца на созданные оверлейные диски
  file:
    path: "{{ user_pool_path }}"
    state: directory
    owner: "{{ user }}"
    group: "learners"
    recurse: yes

- name: Принудительное обновление пользовательского пула Libvirt
  command: "virsh pool-refresh {{ user_pool_name }}"
  failed_when: false
  changed_when: false

- name: Генерация XML-конфигураций виртуальных машин из шаблонов
  template:
    src: "templates/{{ item }}.xml"
    dest: "/tmp/{{ item }}.xml"
    owner: root
    group: root
    mode: '0644'
  loop: "{{ user_domains }}"

- name: Принудительное удаление старых виртуальных машин
  command: "virsh undefine {{ item }} --nvram"
  loop: "{{ user_domains }}"
  failed_when: false

- name: Регистрация (определение) новых виртуальных машин
  command: "virsh define /tmp/{{ item }}.xml"
  loop: "{{ user_domains }}"

- name: Определение пути к рабочему столу обучаемого
  command: "xdg-user-dir DESKTOP"
  become_user: "{{ user }}"
  register: xdg_desktop_path
  changed_when: false
  failed_when: false

- name: Установка дефолтного пути, если xdg-user-dir не вернул результат
  set_fact:
    desktop_path: "{{ xdg_desktop_path.stdout | default('/home/' ~ user ~ '/Desktop') }}"

- name: Создание ярлыков запуска виртуальных машин на рабочем столе
  template:
    src: templates/shortcut.desktop.tmpl
    dest: "{{ desktop_path }}/run_{{ item }}.desktop"
    owner: "{{ user }}"
    group: "learners"
    mode: '0755'
  vars:
    # Если регулярный поиск не нашёл тег <title>, default(item, true) подставит имя виртуальной машины
    vm_title: "{{ lookup('file', 'templates/' ~ item ~ '.xml') | regex_search('<title>(.*?)</title>', '\\1') | first | default(item, true) }}"
    vm_icon: "{{ item }}.png"
  loop: "{{ user_domains }}"
