---
- name: Принудительная остановка старых виртуальных машин
  command: "virsh destroy {{ item }}"
  loop: "{{ user_domains }}"
  failed_when: false
  changed_when: false

- name: Принудительное удаление старых виртуальных машин
  command: "virsh undefine {{ item }} --nvram"
  loop: "{{ user_domains }}"
  failed_when: false

- name: Генерация XML-конфигураций виртуальных машин из шаблонов
  template:
    src: "templates/{{ item }}.xml"
    dest: "/tmp/{{ item }}.xml"
  loop: "{{ user_domains }}"

- name: Регистрация (определение) новых виртуальных машин
  command: "virsh define /tmp/{{ item }}.xml"
  loop: "{{ user_domains }}"

- name: Создание ярлыков запуска виртуальных машин на рабочем столе
  template:
    src: templates/shortcut.desktop.tmpl
    dest: "{{ desktop_path }}/{{ item }}.desktop"
  vars:
    # Если регулярный поиск не нашёл тег <title>, default(item, true) подставит имя виртуальной машины
    vm_title: "{{ lookup('file', 'templates/' ~ item ~ '.xml') | regex_search('<title>(.*?)</title>', '\\1') | first | default(item, true) }}"
    vm_icon: "{{ item }}.png"
  loop: "{{ user_domains }}"
