---
- name: Установка режима сборки initrd.img MODULES=dep
  ansible.builtin.lineinfile:
    path: /etc/initramfs-tools/initramfs.conf
    regexp: '^MODULES='
    line: 'MODULES=dep'
    state: present

- name: Установка быстрого сжатия COMPRESS=zstd при сборке initrd.img
  ansible.builtin.lineinfile:
    path: /etc/initramfs-tools/initramfs.conf
    regexp: '^COMPRESS='
    line: 'COMPRESS=zstd'
    state: present
    
- name: Установка QEMU/KVM
  apt:
    name:
      - qemu-kvm
      - libvirt-daemon-system
      - virt-manager
    state: present
  
- name: Остановка и отключение сети default
  shell: |
    virsh net-destroy default 2>/dev/null || true
    virsh net-undefine default 2>/dev/null || true
  # Чтобы Ansible не считал этот шаг изменением при каждом запуске
  changed_when: false

- name: Удаление конфигурационных файлов сети default
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/libvirt/qemu/networks/autostart/default.xml
    - /etc/libvirt/qemu/networks/default.xml

- name: Копирование XML-шаблонов во временный каталог
  template:
    src: "templates/{{ item }}.xml"
    dest: "/tmp/{{ item }}.xml"
    mode: '0644'
  loop: "{{ virtual_networks }}"

- name: Регистрация, запуск и добавление сетей в автозагрузку
  shell: |
    virsh net-define "/tmp/{{ item }}.xml"
    virsh net-start "{{ item }}" || true
    virsh net-autostart "{{ item }}" || true
    rm -f "/tmp/{{ item }}.xml"
  loop: "{{ virtual_networks }}"
  changed_when: true

- name: Добавление administrator и root в группы виртуализации Astra Linux
  user:
    name: "{{ item }}"
    groups:
      - kvm
      - libvirt
      - libvirt-admin
    append: yes
  loop:
    - "administrator"
    - "root"

- name: Определение дефолтного пула в libvirt
  # Принудительное применение (switch group) прав группы libvirt в текущей SSH-сессии без перезапуска системы
  command: "sg libvirt -c 'virsh pool-define-as {{ system_pool_name }} dir --target {{ system_pool_path }}'"
  register: pool_def
  failed_when: false

- name: Запуск дефолтного пула хранения
  command: "sg libvirt -c 'virsh pool-start {{ system_pool_name }}'"
  failed_when: false

- name: Добавление дефолтного пула в автозагрузку при старте хоста
  command: "sg libvirt -c 'virsh pool-autostart {{ system_pool_name }}'"
  failed_when: false

- name: Проверка наличия измененных файлов в каталоге distros
  shell: "find files/distros -type f -newer files/images/distros.iso -print -quit || true"
  register: is_distro_changes
  delegate_to: localhost
  become: false
  changed_when: false

- name: Сборка files/images/distros.iso из файлов в папке files/distros
  # Объединение сборки ISO и touch в одну задачу через bash, чтобы гарантированно обновить время файла
  shell: >
    genisoimage -input-charset utf-8 -r -J -joliet-long -U -o files/images/distros.iso files/distros &&
    touch files/images/distros.iso
  delegate_to: localhost
  become: false
  when: is_distro_changes.stdout != ""

- name: Копирование образов виртуальных машин из files/images в системный пул
  synchronize:
    # Слэш на конце src задает копирование содержимого каталога, а не самого каталога
    src: files/images/
    dest: "{{ system_pool_path }}/"
    recursive: yes
    delete: no
    archive: yes

- name: Обновление пула хранения Libvirt для обнаружения новых файлов
  command: "virsh pool-refresh {{ system_pool_name }}"
  changed_when: false

- name: Копирование иконок ярлыков из files/icons в системный каталог
  synchronize:
    # Слэш на конце src задает копирование содержимого каталога, а не самого каталога
    src: files/icons/
    dest: "/usr/share/pixmaps/"
    recursive: yes
    delete: no
    archive: yes
