---
- name: Удаление виртуальных машин пользователя {{ user }}
  include_tasks: "destroy_user_domains.yml"

- name: Проверка наличия пользовательского пула
  command: virsh pool-info {{ user_pool_name }}
  register: _user_pool_check
  failed_when: false
  changed_when: false

- name: Получение логического статуса существования пользовательского пула
  set_fact:
    is_user_pool_exist: "{{ _user_pool_check.rc == 0 }}"

- name: Принудительная остановка и удаление пользовательского пула
  command: "{{ item }}"
  with_items:
    - "virsh pool-destroy {{ user_pool_name }}"
    - "virsh pool-undefine {{ user_pool_name }}"
  when: is_user_pool_exist
  failed_when: false

- name: Принудительное удаление каталога пользовательского пула
  file:
    path: "{{ user_pool_path }}"
    state: absent
