---
# Все задачи выполняются от {{ user }}
- name: Проверка наличия пользовательского пула
  command: virsh pool-info {{ user_pool_name }}
  register: _user_pool_check
  failed_when: false
  changed_when: false
  
- name: Получение логического статуса существования пула
  set_fact:
    is_user_pool_exist: "{{ _user_pool_check.rc == 0 }}"

- name: Рекурсивное создание структуры каталогов для пользовательского пула
  file:
    path: "{{ user_pool_path }}"
    state: directory
    mode: '0711'
  when: not is_user_pool_exist

- name: Регистрация, запуск и добавление пользовательского пула в автозагрузку
  # Используем shell вместо command, чтобы работали пайпы и кавычки утилиты sg
  shell: |
    sg libvirt-admin -c "virsh pool-define-as {{ user_pool_name }} dir --target {{ user_pool_path }}"
    sg libvirt-admin -c "virsh pool-start {{ user_pool_name }}"
    sg libvirt-admin -c "virsh pool-autostart {{ user_pool_name }}"
    sg libvirt-admin -c "virsh pool-refresh {{ user_pool_name }}"
  when: not is_user_pool_exist

- name: Поиск базовых образов qcow2 в системном пуле хранения
  find:
    paths: "{{ system_pool_path }}"
    patterns: "*.qcow2"
  register: base_images

- name: Формирование списка из имен виртуальных машин
  set_fact:
    user_domains: "{{ base_images.files | map(attribute='path') | map('basename') | map('regex_replace', '\\.qcow2$', '') | list }}"

- name: Создание оверлейных дисков в пользовательском пуле для всех базовых образов qcow2
  command: >
    qemu-img create -f qcow2 -F qcow2 
    -b "{{ system_pool_path }}/{{ item }}.qcow2" 
    "{{ user_pool_path }}/{{ item }}.qcow2"
  loop: "{{ user_domains }}"
  args:
    creates: "{{ user_pool_path }}/{{ item }}.qcow2"

- name: Принудительное обновление пользовательского пула Libvirt
  command: "virsh pool-refresh {{ user_pool_name }}"
  failed_when: false
  changed_when: false

- name: Создание виртуальных машин пользователя {{ user }}
  include_tasks: "define_user_domains.yml"
