---
- name: Управление учетной записью обучаемого
  hosts: "{{ host }}"
  become: true

  pre_tasks:
    - name: Валидация входных параметров (наличие host и user)
      fail:
        msg: "Ошибка! Не задан параметр host и/или user. Пример: -e 'host=lws-01 user=ivanov'"
      when: (user is not defined) or (host is not defined)
      tags: always

    - name: Проверка, что указанный хост существует в файле инвентаря
      fail:
        msg: "Ошибка! Хост '{{ host }}' не найден в вашем файле инвентаря"
      when: host not in groups['all']

  tasks:
    - name: Получение данных о пользователе из passwd
      ansible.builtin.getent:
        database: passwd
        key: "{{ user }}"
        fail_key: false

    - name: Создание переменной is_user_exist
      ansible.builtin.set_fact:
        is_user_exist: "{{ getent_passwd[user] is defined and getent_passwd[user] is sequence }}"

    - name: Гарантировать наличие первичной группы learners в системе
      ansible.builtin.group:
        name: learners
        state: present

    - name: Интерактивный запрос пароля для нового ученика
      pause:
        prompt: "Введите пароль для создания пользователя {{ user }} на хосте {{ inventory_hostname }}"
        echo: false
      register: password_input
      delegate_to: localhost
      become: false
      when: not is_user_exist

    - name: Интерактивный запрос подтверждения пароля
      pause:
        prompt: "Повторите пароль для подтверждения"
        echo: false
      register: password_confirm
      delegate_to: localhost
      become: false
      when: not is_user_exist

    - name: Проверка совпадения введенных паролей
      fail:
        msg: "Ошибка! Введенные пароли не совпадают. Перезапустите плейбук"
      when: 
        - not is_user_exist
        - password_input.user_input != password_confirm.user_input

    - name: Создание новой учетной записи или обновление параметров существующей
      user:
        name: "{{ user }}"
        group: learners
        groups:
          - kvm
          - libvirt
          - libvirt-qemu
          - libvirt-admin
        append: yes
        shell: /bin/bash
        state: present
        create_home: yes

    - name: Установка пароля для новой учетной записи
      shell: "echo '{{ user }}:{{ password_input.user_input }}' | chpasswd"
      no_log: true
      when: not is_user_exist
