---
- name: Создание ярлыков запуска виртуальных машин
  hosts: "{{ host | default('learners') }}"
  become: true

  tasks:
    - name: Динамическое определение пути к каталогу рабочего стола пользователя
      command: "xdg-user-dir DESKTOP"
      become_user: "{{ username }}"
      register: xdg_desktop_path
      changed_when: false
      failed_when: false

    - name: Установка дефолтного пути, если xdg-user-dir не вернул результат
      set_fact:
        final_desktop_path: "{{ xdg_desktop_path.stdout | default('/home/' ~ username ~ '/Desktop') }}"

    - name: Гарантия существования каталога рабочего стола
      file:
        path: "{{ final_desktop_path }}"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0755'

    - name: Размещение ярлыков запуска виртуальных машин на рабочем столе
      template:
        src: templates/shortcut.desktop.tmpl
        dest: "{{ final_desktop_path }}/run_{{ item }}.desktop"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0755'
      vars:
        # Если регулярный поиск не нашёл тег <title>, default(item, true) подставит имя виртуальной машины
        vm_title: "{{ lookup('file', 'templates/' ~ item ~ '.xml') | regex_search('<title>(.*?)</title>', '\\1') | first | default(item, true) }}"
        vm_icon: "{{ item }}.png"
      loop: "{{ user_domains }}"
