---
- name: Оркестрация удаления учетной записи обучаемого
  hosts: "{{ host }}"
  become: true

  pre_tasks:
    - name: Валидация входных параметров (наличие host и user)
      fail:
        msg: "Ошибка! Не задан параметр host и/или user. Пример: -e 'host=lws-01 user=ivanov'"
      when: (user is not defined) or (host is not defined)
      run_once: true

    - name: Проверка наличия хоста в файле инвентаря
      fail:
        msg: "Ошибка! Хост '{{ host }}' не найден в вашем файле инвентаря"
      when: host not in groups['all']

  roles:
    # Уничтожение пула виртуальных машин обучаемого
    - role: vlab
      vars:
        vlab_action: destroy_user_pool

    # Удаление учетной записи обучаемого
    - role: users
      vars:
        user_action: delete
