---
- name: Получение списка зарегистрированных обучаемых
  hosts: all
  become: false
  gather_facts: false

  tasks:
    - name: Поиск пользователей группы learners
      shell: |
        GID=$(getent group learners | cut -d: -f3);
        [ -n "$GID" ] && getent passwd | awk -F: -v gid="$GID" '$4 == gid {print $1}' | paste -sd, - || echo ""
      register: grep_output
      changed_when: false

