---
- name: Развертывание виртуального полигона на рабочем месте обучаемого
  # Заставляем фильтр default срабатывать не только на отсутствие переменной, но и на пустые строки (или значения false)
  hosts: "{{ host | default('class', true) }}"
  become: true

  # Глобальные переменные окружения для всего плейбука
  environment:
    # Менеджеру apt выполнять установку в полностью автоматическом режиме,
    # отвечая согласием на все всплывающие вопросы
    DEBIAN_FRONTEND: noninteractive
    # Явно разрешаем root управлять Libvirt без ограничений
    LIBVIRT_DEFAULT_URI: "qemu:///system"

  roles:
    - common
    - security
    - vlab 
