---
- name: Развертывание виртуальной инфраструктуры на рабочих местах УТК-СЗИ
  hosts: class
  become: true
  vars:
    system_pool_name: "default"
    system_pool_path: "/var/lib/libvirt/images"
    # Имена виртуальных учебных сетей на рабочих местах обучаемых
    classroom_networks:
      - "intnet"
      - "extnet"

  # Глобальные переменные окружения для всего плейбука
  environment:
    # Менеджеру apt выполнять установку в полностью автоматическом режиме,
    # отвечая согласием на все всплывающие вопросы
    DEBIAN_FRONTEND: noninteractive
    # Явно разрешаем root управлять Libvirt без ограничений
    LIBVIRT_DEFAULT_URI: "qemu:///system"

  tasks:
    - name: Генерация SSH-ключа RSA на управляющем компьютере
      openssh_keypair:
        path: "~/.ssh/id_rsa"
        type: rsa
        # Максимальная стойкость 4096 бит для безопасности
        size: 4096
      delegate_to: localhost
      become: false
      tags: testing

    - name: Автоматическое добавление SSH-ключа в доверенные на целевые хосты
      authorized_key:
        user: administrator
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present
      tags: testing

    - name: Удаление межсетевого экрана ufw
      apt:
        name: ufw
        state: absent
        purge: yes
      tags: testing

    - name: Установка дополнительных пакетов (nftables и rsync)
      apt:
        name:
          - nftables
          - rsync
        state: present
        update_cache: yes
      tags: testing

    - name: Настройка правил межсетевого экрана nftables из шаблона
      template:
        src: templates/nftables.conf
        dest: /etc/nftables.conf
        owner: root
        group: root
        mode: '0644'
      tags: testing

    - name: Запуск nftables, чтобы он монополизировал подсистему netfilter
      service:
        name: nftables
        state: restarted
        enabled: yes
      tags: testing

    - name: Установка метапакета виртуализации astra-kvm
      apt:
        name: astra-kvm
        state: present
      tags: testing

    - name: Принудительная остановка службы firewalld, установленной astra-kvm
      service:
        name: firewalld
        state: stopped
      failed_when: false
      tags: testing

    - name: Маскирование (запрет запуска) службы firewalld
      systemd:
        name: firewalld
        masked: yes
      tags: testing

    - name: Включение и запуск службы виртуализации libvirtd
      service:
        name: libvirtd
        state: started
        enabled: yes
      tags: testing

    - name: Проверка наличия сети default
      command: virsh net-info default
      register: default_net_check
      failed_when: false
      changed_when: false
      tags: testing

    - name: Удаление сети default
      command: "{{ item }}"
      with_items:
        # Принудительно останавливаем сеть
        - "virsh net-destroy default"
        # Удаляем конфигурацию сети системы
        - "virsh net-undefine default"
      loop_control:
        loop_var: item
      when: default_net_check.rc == 0
      # Игнорируем ошибки, если сеть уже остановлена
      failed_when: false
      tags: testing

    - name: Копирование XML-шаблонов сетей intnet и extnet на целевые машины
      template:
        src: "templates/{{ item }}.xml"
        dest: "/tmp/{{ item }}.xml"
      loop: "{{ classroom_networks }}"
      tags: testing

    - name: Проверка статуса новых сетей в libvirt
      command: "virsh net-info {{ item }}"
      register: net_check
      failed_when: false
      changed_when: false
      loop: "{{ classroom_networks }}"
      tags: testing

    - name: Определение сетей в libvirt (если они отсутствуют)
      command: "virsh net-define /tmp/{{ item.item }}.xml"
      loop: "{{ net_check.results }}"
      when: item.rc != 0
      tags: testing

    - name: Запуск виртуальных сетей
      command: "virsh net-start {{ item }}"
      loop: "{{ classroom_networks }}"
      # Если сеть уже запущена, игнорируем ошибку, которую выдаст virsh
      failed_when: false
      tags: testing

    - name: Добавление виртуальных сетей в автозагрузку гипервизора
      command: "virsh net-autostart {{ item }}"
      loop: "{{ classroom_networks }}"
      failed_when: false
      tags: testing

    - name: Добавление администратора и root в группы виртуализации Astra Linux
      user:
        name: "{{ item }}"
        groups:
          - kvm
          - libvirt
          - libvirt-admin
        append: yes
      loop:
        - "administrator"
        - "root"
      tags: testing

    - name: Определение дефолтного пула в libvirt
      # Принудительное применение (switch group) прав группы libvirt в текущей SSH-сессии без перезапуска системы
      command: "sg libvirt -c 'virsh pool-define-as {{ system_pool_name }} dir --target {{ system_pool_path }}'"
      register: pool_def
      failed_when: false
      tags: testing

    - name: Запуск дефолтного пула хранения
      command: "sg libvirt -c 'virsh pool-start {{ system_pool_name }}'"
      failed_when: false
      tags: testing

    - name: Добавление дефолтного пула в автозагрузку при старте хоста
      command: "sg libvirt -c 'virsh pool-autostart {{ system_pool_name }}'"
      failed_when: false
      tags: testing

    - name: Проверка наличия измененных файлов в каталоге distros
      shell: "find files/distros -type f -newer files/images/distros.iso -print -quit || true"
      register: is_distro_changes
      delegate_to: localhost
      become: false
      changed_when: false

    - name: Собрка ISO-образа дистрибутивов из папки files/distros
      # Объединяем сборку ISO и touch в одну задачу через bash, чтобы гарантированно обновить время файла
      shell: >
        genisoimage -input-charset utf-8 -r -J -joliet-long -U -o files/images/distros.iso files/distros &&
        touch files/images/distros.iso
      delegate_to: localhost
      become: false
      when: is_distro_changes.stdout != ""

    - name: Синхронизация образов виртуальных машин из локального каталога files/images в дефолтный пул
      synchronize:
        src: "files/images/"
        dest: "{{ system_pool_path }}/"
        recursive: yes
        archive: yes
        delete: yes

    - name: Синхронизация образов виртуальных машин из локального каталога files/images в дефолтный пул
      synchronize:
        # Слэш на конце src копирует содержимое каталога, а не сам каталог
        src: files/images/
        dest: "{{ system_pool_path }}/"
        recursive: yes
        delete: no
        archive: yes
      tags: testing

    - name: Обновление пула хранения Libvirt для обнаружения новых файлов
      command: "virsh pool-refresh {{ system_pool_name }}"
      changed_when: false

    - name: Синхронизация иконок ярлыков из локального каталога files/icons в системный каталог
      synchronize:
        # Слэш на конце src копирует содержимое каталога, а не сам каталог
        src: files/icons/
        dest: "/usr/share/pixmaps/"
        recursive: yes
        delete: no
        archive: yes
      tags: testing
