---
- name: Развертывание среды виртуализации
  hosts: "{{ host | default('class', true) }}"
  gather_facts: true
  become: true

  environment:
    # Настройка полностью молчаливого режима рабрты apt
    DEBIAN_FRONTEND: noninteractive

  roles:
    - common
    - security
    - vlab
