---
- name: Развертывание среды виртуализации
  # Цель всегда all, а фильтрацию делает флаг -l со списком хостов
  hosts: all
  gather_facts: false
  become: true

  environment:
    # Настройка полностью молчаливого режима работы apt
    DEBIAN_FRONTEND: noninteractive

  # Сбор фактов под введенным или дефолтным remote_user
  pre_tasks:
    - name: Сбор фактов о системе
      setup:

  roles:
    - common
    - security
    - vlab
